config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins,  controllers: { sessions: "admins/sessions", 
                                    registrations: "admins/registrations" }
  get 'clubs/edit'

  get 'clubs/new'

  get 'clubs/show'

  get 'magazine/index' => 'magazine#index'

  get 'welcome/homepage'

  root 'welcome#homepage'
  resources :clubs
  devise_for :users, controllers: { #sessions: "users/sessions", 
                                   omniauth_callbacks: "users/omniauth_callbacks" }

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>FootballOye</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<link href='https://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<%=stylesheet_link_tag "oye" %>
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="scripts.js"></script>
	
</head>
<body>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


	<nav class="navbar navbar-personal menubar navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navmob">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span> 
					</button>
				<a class="navbar-brand logoleft" href=<%= root_path %>>Football Oye!</a>
			</div>
			<div>

				<ul class="nav navbar-nav  navbar-right collapse navbar-collapse" id="navmob">
					<li id="home"><a href=<%=root_path%>>Home</a></li>
					<li id="magazine"><a href=<%=magazine_index_path%>>Magazine</a></li>
					<li id="clubs" class="dropdown">
						<a  class="dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">
							Clubs
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu" aria-labelledby="fixtures">
							<li><a href="/clubs/ManchesterUnited">Manchester United</a></li>
							<li><a href="/clubs/Liverpool">Liverpool</a></li>
							<li><a href="/clubs/Barcelona">Barcelona</a></li>
							<li><a href="/clubs/RealMadrid">Real Madrid</a></li>
							<li><a href="/clubs/Arsenal">Arsenal</a></li>
							<li><a href="/clubs/Chelsea">Chelsea</a></li>
							<li><a href="/clubs/ManchesterCity">Manchester City</a></li>
						</ul>
					</li>
					<li><a href="#">Merchandize</a></li>
					<li><a href="#">The Team</a></li>
					<% if admin_signed_in? %>
					<li><%= link_to('Logout   <span class="glyphicon glyphicon-log-out"></span>'.html_safe, destroy_admin_session_path, :method => :delete) %> </li>
					<% elsif user_signed_in? %>
					<li id="user" class="dropdown">
						<a  class="dropdown-toggle" data-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">
							<%= current_user.first_name %>
							<span class="caret"></span>
						</a>
						<ul class="dropdown-menu" aria-labelledby="fixtures">
							<li><%= link_to('Logout   <span class="glyphicon glyphicon-log-out"></span>'.html_safe, destroy_user_session_path, :method => :delete) %> </li>
						</ul>
					</li>
					<% else %>
					<li><%= link_to('Login   <span class="glyphicon glyphicon-log-in"></span>'.html_safe, user_omniauth_authorize_path(:facebook)) %> </li>
					<% end %>
					
				</ul>
			</div>
		</div>
	</nav>
	<%= yield %>
	<div class="footer" id="footer">
		<p>tass Pakistan</p>
	</div>

</body>
</html>